services:
  - type: web
    name: mikael-session-gen
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
    env: docker          # ‚Üê Render utilise ton Dockerfile
    dockerfilePath: ./Dockerfile